---
name: CI

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      unittest_options:
        description: 'Execute UnitTests with these options. e.g. --test scripts/test/Ticket'
        default: ''
        required: false
        type: string

jobs:
  Selenium-Admin:
    name: Selenium:Admin
    runs-on: ubuntu-latest
    container: debian:10-slim
    
    env:
      DB: mysql
      MYSQL_USER: "otrs"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "otrs"
    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: "otrs"
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_PASSWORD: "secret"
          MYSQL_DATABASE: "otrs"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"

      - name: Install dependencies
        run: .github/workflows/ci/dependencies.sh

      - name: Setup Znuny
        run: .github/workflows/ci/setup.sh

      - name: Run UnitTests
        run: |
          su -c "bin/otrs.CheckSum.pl -a create" - otrs
          su -c "bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Selenium/Agent/Ajax/ErrorHandling" - otrs

      - name: Archive screenshots from selenium
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Download all selenium screenshots
          retention-days: 1
          path: /opt/otrs/var/httpd/htdocs/SeleniumScreenshots/*.png
          if-no-files-found: ignore
